version: 0.2

env:
  parameter-store:
    DB_URL: "PRODDBURL"
    DB_USERNAME: "PRODDBUSERNAME"
    DB_PASSWORD: "PRODDBPASSWORD"
    MAPBOX_KEY: "MAPBOXKEY"

phases:
  build:
    commands:
      - ./gradlew bootJar
      - echo "DB_URL=${DB_URL}">.env
      - echo "DB_USERNAME=${DB_USERNAME}">>.env
      - echo "DB_PASSWORD=${DB_PASSWORD}">>.env
      - echo "MAPBOX_KEY=${MAPBOX_KEY}">>.env

artifacts:
  files:
    /codebuild/output/src2294726856/src/github.com/Al-Esku/fms-backend/scripts/*.sh
    /codebuild/output/src2294726856/src/github.com/Al-Esku/fms-backend/appspec.yml
  discard-paths: yes