INSERT INTO users (email, password, username) VALUES ('president@fencingmidsouth.org.nz', '$2a$10$9BOy0ctXn6TENw87t.039u2/GDOTm4bowt9kJI65mwFmR3rymSLZ6', 'MidSouth');

INSERT INTO event (uuid, name, type, registration_required, registration_link, user_id, description, start_date, end_date) VALUES ('c67ad5a7-a62f-4876-b3a6-952c3c3c518f','National Championships 2023', 'Competition', TRUE, 'asdf', 1, 'The NZ National Senior Championships are in Christchurch for 2023!', '2023-10-21', '2023-10-23'),
                                                                                                                            ('b67ad5a7-a62f-4876-b3a6-952c3c3c518f', 'Mid-South Junior Championships', 'Competition', TRUE, '', 1, 'Mid-South Junior Championships', '2024-03-22 19:00:00+00', '2024-03-24 01:00:00+00'),
                                                                                                                            ('c77ad5a7-a62f-4876-b3a6-952c3c3c518f', 'Mid-South U15 & Cadet Championships', 'Competition', TRUE, '', 1, 'Mid-South U15 & Cadet Championships', '2024-04-05 19:00:00+00', '2024-04-07 02:00:00+00'),
                                                                                                                            ('c68ad5a7-a62f-4876-b3a6-952c3c3c518f', 'Mark Rance Memorial (Ranking E/F/S)', 'Competition', TRUE, '', 1, 'Mark Rance Memorial (Ranking E/F/S)', '2024-05-03 21:00:00+00', '2024-05-06 03:00:00+00'),
                                                                                                                            ('c67bd5a7-a62f-4876-b3a6-952c3c3c518f', 'Keith Mann Memorial', 'Competition', TRUE, '', 1, 'Keith Mann Memorial', '2024-05-17 20:00:00+00', '2024-05-19 02:00:00+00'),
                                                                                                                            ('c67ae5a7-a62f-4876-b3a6-952c3c3c518f', 'Mid-South Open', 'Competition', TRUE, '', 1, 'Mid-South Open', '2024-10-11 19:00:00+00', '2024-10-13 01:00:00+00');
INSERT INTO club (short_name, long_name, description, logo_image) VALUES ('piwakawaka', 'Pīwakawaka Fencing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget tellus sit amet odio interdum gravida. Praesent in mattis nulla. Sed eget ante sit amet tortor convallis scelerisque non sit amet libero. Suspendisse potenti. Suspendisse turpis est, iaculis non sem eget, ultricies efficitur lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula purus, quis fermentum nisl eleifend in. Duis a erat ornare, malesuada urna vitae, viverra mauris. Nulla accumsan orci id nisi fringilla, sit amet lobortis nunc vulputate. Suspendisse non massa eros. Aliquam eget ligula risus. Maecenas vestibulum scelerisque imperdiet. Maecenas blandit sit amet lectus consequat dictum. Duis hendrerit justo nulla, sed pulvinar arcu rhoncus facilisis. Vivamus fringilla gravida urna in dignissim. Donec ac lacus eu quam commodo cursus.\nPellentesque imperdiet hendrerit tortor et rutrum. Duis laoreet ipsum eget tincidunt laoreet. Suspendisse ante egestas, tristique libero metus.', 'piwakawaka.jpg'),
                                                ('tfi', 'The Fencing Institute', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget tellus sit amet odio interdum gravida. Praesent in mattis nulla. Sed eget ante sit amet tortor convallis scelerisque non sit amet libero. Suspendisse potenti. Suspendisse turpis est, iaculis non sem eget, ultricies efficitur lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula purus, quis fermentum nisl eleifend in. Duis a erat ornare, malesuada urna vitae, viverra mauris. Nulla accumsan orci id nisi fringilla, sit amet lobortis nunc vulputate. Suspendisse non massa eros. Aliquam eget ligula risus. Maecenas vestibulum scelerisque imperdiet. Maecenas blandit sit amet lectus consequat dictum. Duis hendrerit justo nulla, sed pulvinar arcu rhoncus facilisis. Vivamus fringilla gravida urna in dignissim. Donec ac lacus eu quam commodo cursus.\nPellentesque imperdiet hendrerit tortor et rutrum. Duis laoreet ipsum eget tincidunt laoreet. Suspendisse ante egestas, tristique libero metus.', 'tfi.jpg'),
                                                ('timaru', 'Timaru Swords Club', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget tellus sit amet odio interdum gravida. Praesent in mattis nulla. Sed eget ante sit amet tortor convallis scelerisque non sit amet libero. Suspendisse potenti. Suspendisse turpis est, iaculis non sem eget, ultricies efficitur lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula purus, quis fermentum nisl eleifend in. Duis a erat ornare, malesuada urna vitae, viverra mauris. Nulla accumsan orci id nisi fringilla, sit amet lobortis nunc vulputate. Suspendisse non massa eros. Aliquam eget ligula risus. Maecenas vestibulum scelerisque imperdiet. Maecenas blandit sit amet lectus consequat dictum. Duis hendrerit justo nulla, sed pulvinar arcu rhoncus facilisis. Vivamus fringilla gravida urna in dignissim. Donec ac lacus eu quam commodo cursus.\nPellentesque imperdiet hendrerit tortor et rutrum. Duis laoreet ipsum eget tincidunt laoreet. Suspendisse ante egestas, tristique libero metus.', 'placeholder.jpg'),
                                                ('ucfc', 'University of Canterbury Fencing Club', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget tellus sit amet odio interdum gravida. Praesent in mattis nulla. Sed eget ante sit amet tortor convallis scelerisque non sit amet libero. Suspendisse potenti. Suspendisse turpis est, iaculis non sem eget, ultricies efficitur lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula purus, quis fermentum nisl eleifend in. Duis a erat ornare, malesuada urna vitae, viverra mauris. Nulla accumsan orci id nisi fringilla, sit amet lobortis nunc vulputate. Suspendisse non massa eros. Aliquam eget ligula risus. Maecenas vestibulum scelerisque imperdiet. Maecenas blandit sit amet lectus consequat dictum. Duis hendrerit justo nulla, sed pulvinar arcu rhoncus facilisis. Vivamus fringilla gravida urna in dignissim. Donec ac lacus eu quam commodo cursus.\nPellentesque imperdiet hendrerit tortor et rutrum. Duis laoreet ipsum eget tincidunt laoreet. Suspendisse ante egestas, tristique libero metus.', 'ucfc.png'),
                                                ('united', 'United Fencing Club', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget tellus sit amet odio interdum gravida. Praesent in mattis nulla. Sed eget ante sit amet tortor convallis scelerisque non sit amet libero. Suspendisse potenti. Suspendisse turpis est, iaculis non sem eget, ultricies efficitur lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula purus, quis fermentum nisl eleifend in. Duis a erat ornare, malesuada urna vitae, viverra mauris. Nulla accumsan orci id nisi fringilla, sit amet lobortis nunc vulputate. Suspendisse non massa eros. Aliquam eget ligula risus. Maecenas vestibulum scelerisque imperdiet. Maecenas blandit sit amet lectus consequat dictum. Duis hendrerit justo nulla, sed pulvinar arcu rhoncus facilisis. Vivamus fringilla gravida urna in dignissim. Donec ac lacus eu quam commodo cursus.\nPellentesque imperdiet hendrerit tortor et rutrum. Duis laoreet ipsum eget tincidunt laoreet. Suspendisse ante egestas, tristique libero metus.', 'united.png'),
                                                ('waimate', 'Waimate Swords Club', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget tellus sit amet odio interdum gravida. Praesent in mattis nulla. Sed eget ante sit amet tortor convallis scelerisque non sit amet libero. Suspendisse potenti. Suspendisse turpis est, iaculis non sem eget, ultricies efficitur lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula purus, quis fermentum nisl eleifend in. Duis a erat ornare, malesuada urna vitae, viverra mauris. Nulla accumsan orci id nisi fringilla, sit amet lobortis nunc vulputate. Suspendisse non massa eros. Aliquam eget ligula risus. Maecenas vestibulum scelerisque imperdiet. Maecenas blandit sit amet lectus consequat dictum. Duis hendrerit justo nulla, sed pulvinar arcu rhoncus facilisis. Vivamus fringilla gravida urna in dignissim. Donec ac lacus eu quam commodo cursus.\nPellentesque imperdiet hendrerit tortor et rutrum. Duis laoreet ipsum eget tincidunt laoreet. Suspendisse ante egestas, tristique libero metus.', 'placeholder.jpg');

INSERT INTO roles (name) VALUES('ROLE_ADMIN');

